### ISSUE TITLE
Suggestion: allow creation of DS/i cart ROM dump metadata file

### ISSUE THREAD

**Issue by mariomadproductions** [DS-Homebrew/GodMode9i#101]
I think it'd be a good idea if GodMode9i had a dump metadata file that could be created, like wooddumper and GodMode9 (and CleanRip). For example, in GodMode9's gamecart "virtual directory", there's a text file named like the ROM file, but with a .txt extension. Here's an example from GM9:
```
Title String : NEW MARIO
Product Code : A2DP01
Revision     : 0
Cart ID      : 00001FC2
Platform     : DS
Save Type    : SPI
Save chip ID : 0xFFFFFF
Timestamp    : 2021-07-09 19:48:01
GM9 Version  : v2.0.0
```

I think the most important here (for ROM preservation purposes) are the Cart ID, Timestamp and dumping tool version, but these are all useful.

**Comment by Dimensional** [comment]
That would be a good thing, if all of it is possible. Would be useful if users want to upload that info to No-Intro. If it was possible, might even provide checksums in the metadata file, possibly encrypted and decrypted.

**Comment by mariomadproductions** [comment]
Yeah checksums could be useful, except I think they can be calculated much faster on PC. Although maybe the DSi has accelated support for some kind of checksum(s) (like 3DS does for SHA256).

**Comment by Dimensional** [comment]
True, it may be difficult for some of the higher end checksums, however No-Intro supports CRC32, MD5, SHA1, and SHA256 for some dumps. I just looked at some of the most popular games, specifically pokemon, on their database, and not a lot of them have SHA256.

**Comment by lifehackerhansol** [comment]
Doesn't GM9i have a SHA1 function? That seems to be pretty widely accepted on DAT-o-MATIC.

**Comment by Peter0x44** [comment]
> DSi has accelerated support for some kind of checksum(s)
The DSi BIOS has sha1 functions, which are what GodMode9i currently uses.
They seem to be pretty slow though... obviously not intended for data as large as a rom
I remember timing it, 512mb took about ~7 minutes
I also made a version using some crc32 code I found, it did work but it took even longer (512mb took over 15 minutes)
I did want to get around to implementing a fallback software sha1 implementation so it isn't limited to the DS, but I never really got around to doing that
