### ISSUE TITLE
Ability to see ROM info before dumping

### ISSUE THREAD

**Issue by zurgeg** [DS-Homebrew/GodMode9i#117]
I.e., Size, TID, Etc., etc.,

Would be nice if you're low on SD space

**Comment by lifehackerhansol** [comment]
I second this. Something like "Show file info", an option in GodMode9 when you select a file or a cart, would be a nice-to-have.

**Comment by zurgeg** [comment]
> I second this. Something like "Show file info", an option in GodMode9 when you select a file or a cart, would be a nice-to-have.

I might make a PR, but I don't have much knowledge of C++.

Also, iirc GM9 has that shown on the bottom screen. IDK though, I haven't used it for awhile

**Comment by lifehackerhansol** [comment]
It is on the bottom display, yes. Just opened it right now to see what it's like.

It also has the ability to change file attributes, etc, but just seeing the file details is good enough for me.
