### ISSUE TITLE
Cannot browse files on Acekard 2i outside of TWLMenu++

### ISSUE THREAD

**Issue by malvarenga123** [DS-Homebrew/GodMode9i#135]
Hi, according to the readme, browsing files on the Acekard 2i should be possible without launching GM9i from TWLMenu++.
But when I launch it directly from the 2DS NAND (installed from CIA), the `[fat:] FLASHCARD (NDS)` item doesn't show up.
When I launch the NDS version from TWLMenu++, I can see `[fat:] FLASHCARD (NDS)` and browse the flashcard normally.

I think I have the latest firmware on the Acekard (2DS sees it as ALEXANDRA LEDERMANN DS UBISOFT)
GodMode9i version: 3.1.0

**Comment by Epicpkmn11** [comment]
Try with the build from #136, the current release doesn't work at all for me (TWiLight, Unlaunch, or CIA) and that fixes it for me at least

**Comment by malvarenga123** [comment]
Thanks @Epicpkmn11. The CIA worked for me.
