### ISSUE TITLE
No game cartridge option on Godmode9i??

### ISSUE THREAD

**Issue by LavenderShine** [DS-Homebrew/GodMode9i#165]
Hello, everyone. I'm new to DS modding, so please excuse my low-knowledge on it.

I've lately been facing an issue with Godmode9i. When I load it (through TWiLight Menu++, that is), I get to a menu of this:
[sd:] SDCARD (MICROSDXC)
[nand:] SYSNAND
{ram:] RAMDRIVE
[nitro:] NDS GAME IMAGE

I click on the sd option and I see the root of my sd card, which has some files (duh) and these folders:
00030004 -- this is for wood dumper. not important in this case.
_gba -- for gbarunner2.
_nds -- has a lot of stuff, but carries the "nds-bootstrap" folder (which has a bunch of BIN files) and the "TWiLightMenu" folder.
gm9i -- has "config.ini" file. no idea what purpose it server. (if it server any.)
photo -- an empty folder.
private -- a chain for the "pit.bin" file.
(apparently, it also has "System Volume Information" folder? inside it, there's "IndexerVolumeGuid" and "WPSettings.dat" no clue what it is for????)

I click on the nand option, and I see these folders:
import -- empty.
progress -- empty.
shared1 -- has "TWLCFG0.dat" and "TWLCFG1.dat" files
shared2 -- has a "launcher" folder with "wrap.bin" file in it, and "0000" file.
sys -- has a "log" folder and a bunch of other files.
ticket -- has five folders, named with numbers, and each one of them has at least 1 ".tik" file.
title -- five folders, but this time it has a mumbo jumbo of content in it. doesn't seem to be important.
tmp -- chain of folders to nothing.

I click on the ram option, and it has nothing.

I click on the nitro option, and there's two folders within:
fonts -- has a "misaki-gothic-8x8.frf" file.
languages -- need I say more?

and there's no Game Card option. does anyone know if there's something wrong? or am I being a fool?

also, there's the "START menu" option in the bottom screen. I press the "START" button of my DSi to head there, then I go to the "Title Manager" and I see this:
Brain Age Express (happens to be in the DSi's menu, works fine too. don't remember when did I get it or how lol.)
Brain Age Express: Math (same with the above)
DS Download Play
Flipnote Studio
then the DSi's casual apps, such as the camera, the shop, photo clock, etc. there's also a "NINTENDO DS (with a trademark)".

and side note: I'm trying to dump MKDS to the SD Card to play it on my PC.

I'd really appreciate your help, gamers!

**Comment by Peter0x44** [comment]
Do you have Unlaunch installed? It is required to dump cartridges, as mentioned on http://wiki.ds-homebrew.com/godmode9i/#dumping-functionality

**Comment by LavenderShine** [comment]
> Do you have Unlaunch installed? It is required to dump cartridges, as mentioned on http://wiki.ds-homebrew.com/godmode9i/#dumping-functionality

okay, now I installed the Unlaunch, followed on with the tutorial and it worked! thank you very much for helping out, I truly appreciate it from the bottom of my heart! <3
