### ISSUE TITLE
Better Macro/single-screen support

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/GodMode9i#168]
At the moment, GM9i is mostly usable with just the bottom screen, but you can only see the currently selected file or drive. There are a few ways this could be mitigated.

My preferred way would probably be the option to show everything on the bottom screen, but instead of all of the controls being listed, it only shows "SELECT - Controls," which would display the currently usable controls (along with the basic file info and GM9i version) at any time while held, but maybe there are better solutions. Even just support for swapping screens would be good.

**Comment by Epicpkmn11** [comment]
It actually already supports swapping screens on touching the touch screen, it's just locked behind compile time #ifdefs so you need to make a special build. A simple way to make that more useful would be to add it to the START Menu, I'll look into that soon.
