### ISSUE TITLE
128KB EEPROM save file is shifted by 1 byte

### ISSUE THREAD

**Issue by Ixaruz** [DS-Homebrew/GodMode9i#169]
I tried dumping the save file from the game Pokémon Mystery Dungeon: Explorers of Sky.
when loading the dumped save file in nds-bootstrap, desmume or melonDS, the game proceeds as if no save file is present.
Therefore i did a little digging and stumbled upon [this issue](https://github.com/Arisotura/melonDS/issues/344), which mentions using TWLSaveTool on the 3ds for EEPROM 128KB games.
That tool has worked for me, however I wish GM9i would do the same, since I want to dump saves for my DSi, so i checked the difference in the files.
 
 Gm9i has a bitshift in the file by 1 byte.

 
 | TWLSaveTool | GodMode9i |
| --- | --- |
| ![Screenshot_2](https://user-images.githubusercontent.com/44379110/172000554-2a9f188d-4849-41e7-9d73-40bf4b372299.png)| ![Screenshot_1](https://user-images.githubusercontent.com/44379110/172000569-bd298ee1-7414-4110-ac76-49db3f9dc180.png) |

The rest of the save file is identical, though it obviously is missing 1 byte at the end due to the bitshift and the set size of 128KB.

This issue is limited to said cartridge type, as other cartridges I tested did not have this issue.

**Comment by Epicpkmn11** [comment]
Are you using the [latest version](https://github.com/DS-Homebrew/GodMode9i/releases/latest)? Cause this should've been fixed by [v2.7.0](https://github.com/DS-Homebrew/GodMode9i/releases/tag/v2.7.0).

**Comment by Ixaruz** [comment]
hi, yes latest version. 
Also I already checked the commits in that version and i think it might be an issue in libnds?

**Comment by RocketRobz** [comment]
> hi, yes latest version.

So you *are* using v2.7.0, or what version is shown when you start up GodMode9**i**?

**Comment by Ixaruz** [comment]
Ok, I did a sanity check and came to the following result:
2.7.0 works and dumps the save properly, the latest version([v3.2.1](https://github.com/DS-Homebrew/GodMode9i/releases/tag/v3.2.1)) however always creates that bitshift.

**Comment by Epicpkmn11** [comment]
Oops typo'd the "fixes" thing in #170, should be fixed by that.

It's weird, but if it works it works I guess.

**Comment by Ixaruz** [comment]
I have no idea why THIS would fix it, but thanks so much!
