### ISSUE TITLE
Tap character in keyboard/hex editor to change cursor position

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/GodMode9i#176]
A feature in keyboards like that of the DSi Browser or DSOrganize is the ability to touch a position in the text being edited while the keyboard is open to move the cursor to that location. This would be a nice QoL sort of thing, especially if GM9i ever gets a text editor.

**Comment by Zurlon** [comment]
I agree, especially with reference to my feature request #179
