### ISSUE TITLE
Folder navigation feature request

### ISSUE THREAD

**Issue by Zurlon** [DS-Homebrew/GodMode9i#177]
Feature request

When scrolling through a list of folders, if you enter a folder and then return to the list in the parent folder, the currently selected item would be the folder you just entered. 

This would make navigating a list of folders much easier, as currently the view simply resets to the double dots at the top of the list. If the list is 2+ screens long this can be extremely jarring. This would solve that issue completely.

**Comment by NightScript370** [comment]
I think it should only do this if you hit the "..." folder in the ROM navigation. That way, it still looks like its within the navigation system, and those who don't like it could use B to get the old mechanism back.

"But the '...' is so far"
It's typically on the first page, which you can access by repeatedly hitting the L button.

**Comment by Zurlon** [comment]
I am in favour of the inverse of that: double dots takes you to the double dots of the parent folder, B button takes you back to where you were in the parent folder. Ultimately it is a design choice for the devs, if the feature is there somewhere I am not too concerned about the implementation although I do have a preference.
