### ISSUE TITLE
Select all feature request

### ISSUE THREAD

**Issue by Zurlon** [DS-Homebrew/GodMode9i#178]
Feature request

When the double dots at the top of a folder is highlighted, pressing the L shoulder button and the A button would select all items within that folder.

I have found that, especially when managing the screenshots that this app produces, a select all feature would be very useful. This seems like a simple uncomplicated feature, and it would match the thematic use of the L shoulder button to select multiple items. It could be an unlisted feature like L+A/R+A on the double dots to return to the top level navigation page (obviously this suggestion would replace current L+A functionality).

**Comment by Epicpkmn11** [comment]
This actually already exists, <kbd>L</kbd> + <kbd>Right</kbd> to select all, <kbd>Left</kbd> to deselect all.
