### ISSUE TITLE
Clock format bug fix request

### ISSUE THREAD

**Issue by Zurlon** [DS-Homebrew/GodMode9i#184]
Bug fix request

As far as I can see, the clock in the top right of the top display is formatted in such a way where a one digit hour number (1-9) is prefaced with a space, but a two digit hour number (10 onwards) is not prefaced with a space. I assume this is for consistency so the clock always occupies a certain number of digits.

However, for long file paths that reach all the way to the end of the top bar on the top screen there can be an issue. If the clock is displaying a two digit hour number then there is no gap between the end of the file path and the start of the clock. This looks very strange, and even stranger if the file path ends with a number. A one digit hour number does not cause this issue due to the space before the first clock digit.

Adding a space character either at the end of the file path, or before the clock, if the time is 10am or greater would solve this issue. If clock width consistency is a goal then always add an extra space; that way, the file path would always end at the same location on the top screen. Design choice.

(Also you could display the clock in a hh:mm format regardless of the time, plus a spacer to solve this issue - if that is possible I would personally prefer it).

Top screen example: (120 o'clock?)

![image](https://user-images.githubusercontent.com/15965623/182604488-0d636cad-b0c1-4ac6-a9e2-6c0b34cbcf12.png)

But when its a one digit hour number there is no issue:

![image](https://user-images.githubusercontent.com/15965623/182606659-e7094a5d-361e-4d40-84b1-fb13d47943e2.png)

(Alternatively, or as well as, could there be an option in the config.ini to hide the clock completely? I think I would disable the clock if I could.)

**Comment by Epicpkmn11** [comment]
Switched to zero-padded with a forced (no-break) space at the start with #185, if you want that now can just download the English ini and set it manually in the config ini. If you want to disable the clock entirely simply edit a language ini to set:
```ini
TIME_FORMAT=
```
