### ISSUE TITLE
Release builds as individual binaries

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/GodMode9i#186]
As it is, GM9i is distributed as a 340 KB 7z archive, containing the `cia`, `dsi`, and `nds` version. The individual builds are nearly three times this size each, but given how small it is, I wouldn't think it would be much of an issue to deliver them this way.

The main reason for doing this would be for compatibility with downloading directly to the DS(i) through Universal-Updater or dsidl. These systems can't really extract 7z archives as far as I know (due to memory limitations), so there's no way to download and use builds from the console itself.

**Comment by Epicpkmn11** [comment]
I agree with this, even on console the size difference isn't very important for download speed and it's less confusing imo.

I think we could keep the 7z for compatibility with existing downloaders and guides and such, but just add the other files for the next release. I'll make a PR to add it to the building.yml unless someone else gets to it first.

**Comment by spellboundtriangle** [comment]
Solved in #191
