### ISSUE TITLE
Clock format issue

### ISSUE THREAD

**Issue by Zurlon** [DS-Homebrew/GodMode9i#187]
From PR #185:

![image](https://user-images.githubusercontent.com/15965623/183701305-b56ecab1-e241-44c4-b3f1-97b678aca60d.png)
%I is 12-hour clock, zero padded. %H is 24-hour clock, zero padded. I have changed it from %I to %H in a local language.ini and tested it and it works.

Secondly, there is now an issue with how the file path is displayed. The final character of the file path is cut off when using any of the time formats (either the old %k, %I or %H). This is caused by the space inserted before the placeholders in the TIME_FORMAT entry in the language.ini. I obviously don't know how the code works but visually it seems like there is a problem with the end point of the file path and this new space character is overlaid on top of the last file path character, hiding it. Removing the space fixes the issue but of course brings back the 120 o'clock problem from #184.

Examples:

![image](https://user-images.githubusercontent.com/15965623/183703028-74fa1c35-797c-40a5-bab1-15dcebb5146c.png) (should be "del1" at the end of the filepath)

![image](https://user-images.githubusercontent.com/15965623/183703066-5d0a6ce9-47d2-4da2-be14-9ff9dab6cfec.png) (should be "del2" at the end of the filepath)

**Comment by Epicpkmn11** [comment]
Oh whoops, I think I tested at 12:XX my time so I didn't notice that `%I` is 12-hour, I misremembered that one being 24-hour... I'll fix that and the alignment issue in a sec
