### ISSUE TITLE
[Feature Request] add cart dump .txt file, like GodMode9

### ISSUE THREAD

**Issue by mariomadproductions** [DS-Homebrew/GodMode9i#200]
It would be useful for preservation (e.g. No-Intro) if a txt file like this was outputted beside the .gba/.nds/.dsi file, like with GodMode9:
```
Title String : GAME NAME
Product Code : XXXX##
Revision     : #
Cart ID      : XXXXXXXX [for DS/DSi only]
Platform     : GBA/DS/DSi
Timestamp    : YYYY-MM-DD HH:MM:SS
GM9i Version : x
```
This makes it easy to keep track of dumps and avoids having to manually gather this info.
Thanks

**Comment by Epicpkmn11** [comment]
GodMode9i has already had this for several versions, dump "Metadata"

**Comment by mariomadproductions** [comment]
> GodMode9i has already had this for several versions, dump "Metadata"

Sorry lol, that was mindless of me, I made this request before and it was added.
