### ISSUE TITLE
[Bug Report] Dumping some GBA save files adds extra bytes

### ISSUE THREAD

**Issue by BurstClouds23** [DS-Homebrew/GodMode9i#217]
Hello, I recently got some issues while I dump my GBA save files via godmode9i, sometimes I get 16 extra bytes on the .sav and difficulties emulators compatibility.
But when I dump it with GBA Backup Tool, it removes that 16 bytes from my game (the only bad thing that I must to reset my console every time when I use it and is kinda anoying)

**Console info:**
  - [x] DS/DSi/3DS using a Flashcard
  - [ ] DSi (Using SD card)
  - [ ] 3DS (Using SD card)
- gm9i Version: [v3.4.1]
- Game: Pokemon Ruby and Emerald Spanish version

Note: Can you add something in the next version to remove that extra bytes? thanks for hearing me

![Cartridge dump using GBA Backup Tool](https://user-images.githubusercontent.com/131524279/233778138-4d03e773-3f62-45ee-88f3-033881f67102.png)
![Cartridge dump using gm9i](https://user-images.githubusercontent.com/131524279/233778139-11130f5f-ee95-435a-b6da-153a4b963f6c.png)
![Cartridge info](https://user-images.githubusercontent.com/131524279/233778140-45d469ef-8789-41e9-b650-be4583883da8.png)

**Comment by Epicpkmn11** [comment]
That's the mGBA RTC footer (#205) (huh, I missed that, didn't realized GM9i supported that)

I think it would be smart to add dumping options for `(No RTC)`, I'll look into it soon
