### ISSUE TITLE
[Feature request] Want GM9i 3.1.0's file renaming method back

### ISSUE THREAD

**Issue by MelonGx** [DS-Homebrew/GodMode9i#225]
Every time I backup several same-title DS carts' savedata, I find current Godmode9i's method is inconvenient:
In order to type my own phrase of filename for easy managing all my save backups, I have to delete every single alphabet (including extension).
The time delay of deleting a large amount of alphabets make me nervous.

But with Godmode9i 3.1.0, I can simply clear all the filename and retype my own phrase.
It's super convenient.
So I want it back.

**Comment by spellboundtriangle** [comment]
I think it would be better to just add the ability to clear the text by pressing X or something

**Comment by MelonGx** [comment]
> I think it would be better to just add the ability to clear the text by pressing X or something

This is also acceptable.
