### ISSUE TITLE
Remounting SD Card Freezes the DSi

### ISSUE THREAD

**Issue by ChampionLeake** [DS-Homebrew/GodMode9i#3]
Usage of Unmounting the SD Card works perfectly fine. That is until you want to Remount your SD card with the key combo(R+B), the system just hangs leaving you forced to shutdown the DSi.

**Comment by RocketRobz** [comment]
Yeah, idk why this happens. :P

**Comment by FlameKat53** [comment]
Yeah, this happens on flashcards too (when running from Flashcard)
