### ISSUE TITLE
fwTool features

### ISSUE THREAD

**Issue by redstonekasi** [DS-Homebrew/GodMode9i#50]
As you uave added support for reading the nand,
it may be a good idea to add nand operations. Or stuff like that.

**Comment by RocketRobz** [comment]
You mean like writing to it?
This isn't added because the NAND chip is old, and it doesn't write to both FAT copies.

**Comment by redstonekasi** [comment]
No, sorry if it was unclear.
I meant adding features likes NAND backups or getting Console ID.
________________________________

**Comment by urmum-69** [comment]
Getting the console ID would be pretty trivial to implement, although it would be next to useless
I think the NAND backup is really out of scope for GodMode9i and should be left to dumpTool instead. You can easily get the Console ID and NAND cid from the Nocash footer dumpTool creates.
I don't think it belongs as a feature here.
