### ISSUE TITLE
support writing saves to DS game cards

### ISSUE THREAD

**Issue by zigg** [DS-Homebrew/GodMode9i#56]
I'd love to be able to restore saves to DS game cards as well as dump them.

I think libnds already has the support? I was once trying to write a TFTP-based save tool ~10 years ago and I believe `cardWriteEeprom` should do the trick.

**Comment by Nintendo-png** [comment]
What about other types of saves, like NAND

**Comment by zigg** [comment]
@Nintendo-png Do you mean Flash saves, like these? https://github.com/devkitPro/libnds/blob/105d4943dbac8f2bd99a47b22cd3ed48f96af083/source/common/cardEeprom.c#L122

I'm not aware of DS game cards having saves other than EEPROM or Flash, and devKitPro's support _should_ cover them all, I think.
