### ISSUE TITLE
2GB+ SD support

### ISSUE THREAD

**Issue by ZeikkuSSJ7** [DS-Homebrew/GodMode9i#58]
When I start GodMode9i with my 32GB SD it stucks before "mounting drives" appears (even if it is a 4GB SD). I have another 2GB SD and it boots fine, but I would like to use only my 32 GB one.

**Comment by NightYoshi370** [comment]
Do you have hiyaCFW on that 32GB SD card

**Comment by ZeikkuSSJ7** [comment]
Yes, but I have tried booting from Unlaunch and TwilightMenu and nothing, its stuck on the same place. Does it matter to have it installed? On the 2GB SD card I have it installed too.

**Comment by monek30** [comment]
can i use SD x NTR support on 3DS? I tried with no success

**Comment by RocketRobz** [comment]
Just add `SLOT1_ENABLESD = 1` to `sd:/_nds/TWiLightMenu/settings.ini`, above `[NDS-BOOTSTRAP]`.

**Comment by monek30** [comment]
yes i did it, this is what i t've tried:
1)to run godmode9i.nds via twilightmenu on SD Card and i only see the option to dump my r4
2)to run godmode9i via twilightmenu on DS Flashcard and i only see my R4 files

**Comment by RocketRobz** [comment]
Did you launch your R4 using TWiLight Menu++?

**Comment by monek30** [comment]
I've tried
1) launch twilightmenu from 3ds SD card -> launch godmode9i.nds from 3ds sd card -> after that i can see 3ds root and info that i can dump my flashcard
2) launch normal my flashcard with twilightmenu installed -> launch godmode9i.nds and after that i can only see my flashcard files
3) now i've tried to start twilightmenu from 3ds sd card-> boot flashcard from twilighmenu-> start godmode9i from flashcard and i can see "no drives found!"
