### ISSUE TITLE
Add support for slot2 flashcards

### ISSUE THREAD

**Issue by mariomadproductions** [DS-Homebrew/GodMode9i#74]
It would be useful if GM9i had support for slot2 flashcarts, as you could dump DS cart ROMs to them. There is wooddumper r89 slot2, but it doesn't work on some slot2 flashcarts, is closed source and isn't updated anymore.

**Comment by lifehackerhansol** [comment]
This is very late, but... wasn't this implemented in https://github.com/DS-Homebrew/GodMode9i/releases/tag/v2.0.1?

I don't have a GBA cart to test, so please double check.

**Comment by RocketRobz** [comment]
This has been implemented some versions ago, and yes, it does work.

**Comment by DraconicNEO** [comment]
> This is very late, but... wasn't this implemented in https://github.com/DS-Homebrew/GodMode9i/releases/tag/v2.0.1?
> 
> I don't have a GBA cart to test, so please double check. It does require DLDI support for said flashcard.

Tested on Supercard SD and it just Freezes with a White screen. I know I'm using the correct DLDI patch because another DLDI patched homebrew boots and works just fine.
