### ISSUE TITLE
Pressing X while having a folder in your clipboard deletes the folder in your clipboard

### ISSUE THREAD

**Issue by gek169** [DS-Homebrew/GodMode9i#80]
I was trying to copy my saves from my flash cart to my SD card.
I decided to try to delete the folder on my SD card before pasting the folder from the flash cart

To be clear here's the order of events
* Use twilight menu on SD card on New3DSXL to launch into Twilight menu on flash cart, SCFG + SD access enabled.
* Open Godmode9i on the flashcart
* Navigate to fat:/roms/NDS/ and copy "saves" to the clipboard
* Navigate to sd:/roms/NDS/ and press X on the existing saves directory.
* The existing saves directory on sd:/ will still exist but the one on the flashcart is now deleted

The expected behavior is that X does not touch your clipboard at all and only deals with the selected item in the menu... like it does if you don't have something in your clipboard.

After deleting the folder on the sd card, I found that it was still there, but the one on my flashcart, which was in my clipboard, was gone.

your jank code lost my save game >:( I have to replay 2 entire worlds of kirby squeak squad and get the treasures again.

**Comment by Epicpkmn11** [comment]
It could be made more clear in the deletion message, but that's not "jank code", that's the intended behavior... #67 added that

**Comment by gek169** [comment]
well undo it 
it's bad
software should behave the same way on the same screen where most convenient

lost me my orcs and elves dungeon save too, I had beaten the great hall

**Comment by gek169** [comment]
who are these people who let these horrible anti-user features get added to the software

**Comment by NightYoshi370** [comment]
> who are these people who let these horrible anti-user features get added to the software

There's a difference between bringing up a legitimate complain and attacking + ranting. We understand that you're frustrated, yet this is not the mature way to handle it.

**Comment by gek169** [comment]
OK I'll admit it's a bit childish to go outright and say it's "horrible"
Here's a legitimate, intellectual critique:
In user interface design it is best to make mode switching (change in the functionality of buttons or actions) extremely clear to the user.

Godmode9i makes no indication that the delete button now deletes the file in your clipboard (Which is pointless. In what situation would you copy a file to your clipboard, and then want to delete it? Why wouldnt you just delete it when you highlight it? NONE.) 

Mode switching of the UI is occuring with little indication to the user, they just have to "know" that when they have something in the clipboard, they're in "clipboard mode" and they can't delete files.

and yes I am frustrated I lost all my saves 
You should at least add a warning to it
WARNING YOU ARE DELETING YOUR CLIPBOARD!!!!
in big text because nobody is gonna expect that it deletes the thing in your clipboard they think it just deletes the file they're hovering over, like it does normally

you know I want to find this guy who made this commit, give him an earful

**Comment by unresolvedsymbol** [comment]
Nobody here is entitled to writing software for you to (mis)use, nonetheless I'll clean some stuff up

**Comment by Epicpkmn11** [comment]
I'm already working on changing it to have split selection and clipboard btw, so before you do anything probably best to wait for me to finish, I'm almost done anyways

**Comment by gek169** [comment]
Thank you Evie, you're a life saver
