### ISSUE TITLE
Busy Folders: Flickering while scrolling and other issues

### ISSUE THREAD

**Issue by oneilmw** [DS-Homebrew/GodMode9i#90]
I have a folder on my SD card.
It has **398 files** on it.
It takes twelve seconds to enter the directory.
When highlighting new files using UP or DOWN, even if the screen doesn't scroll (such as when trying to select a vertically off-screen folder item), the screen flashes black.  It does so every time.
Also, it's hard to tell, but I think the max scroll speed is about half as fast as it should be (testing required).
Of course, the obvious solution is to have not **398 files** in a single folder.  I'm working on it, but I might still have like at least 150 a pop.
Good thing I don't have photosensitive epilepsy.
GM9i v2.6.1

**Comment by Epicpkmn11** [comment]
Flickering is fixed by #105, I haven't tested with huge folders yet though so I don't know if it fixes scrolling slowly
