### ISSUE TITLE
Add DSiWare nds-bootstrap support

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/GodMode9i#91]
As of 2.6.1 and nds-bootstrap 0.39.0, bootstrapping DSiWare will attempt to use `.sav` files in the */saves folder, instead of `.pub`/`.prv`. It then displays black and white screens (tested with Cave Story, UNO, and NDSi Browser).

**Comment by RocketRobz** [comment]
Loading .nds files via nds-bootstrap has been removed. Closing.
