### ISSUE TITLE
Can't dump NAND save carts

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/GodMode9i#96]
GodMode9i will not read large cards such as WarioWare DIY and Pokemon White, despite the DSi Menu displaying the card's banner with no issues.

**Comment by tomrow** [comment]
Nevermind, can't quite reproduce after restarting, closing now.

**Comment by tomrow** [comment]
I managed to get Pokemon to dump, but WarioWare is still failing, despite booting the game successfully.

**Comment by Epicpkmn11** [comment]
I think this is the same issue for Face Training (though that one may have additional problems) so I've renamed to NAND save carts in general.

Making [read_card.c:177-187](https://github.com/DS-Homebrew/GodMode9i/blob/master/arm9/source/read_card.c#L177-L187) to be run even in DSi Mode fixes reading the header for Face Training, but the rest of the ROM is garbage.
